name: JD Sign Bot
on:
    push:
        branches:
            - master
    schedule:
        - cron: "00 20 * * *"
        - cron: "00 4 * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run app
              run: npm install
            - run: node app.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
                IS_NOTIFY_RES: ${{ secrets.IS_NOTIFY_RES }}
                TG_BOT_API_SECRET: ${{ secrets.TG_BOT_API_SECRET }}
                TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
